'use client'

import { useEffect, useState } from 'react'
import { hitungWeton, pasanganIdeal } from '@/lib/weton-data'
import { Arrow, DateField, Disclaimer, formatDate, InfoBlock, SectionTitle, ShareButtons, WetonCard, WetonShell } from '@/components/weton-header'

export default function WetonPage() {
  const [date, setDate] = useState('')
  const [maghrib, setMaghrib] = useState(false)
  const [result, setResult] = useState<ReturnType<typeof hitungWeton> | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('tgl'); if (value) { setDate(value); calculate(value, false) } }, [])
  function calculate(value = date, night = maghrib) { setError(''); if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) { setResult(null); setError('Masukkan tanggal lahir terlebih dahulu.'); return } const [y, m, d] = value.split('-').map(Number); const parsed = new Date(`${value}T00:00:00`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== value) { setResult(null); setError('Tanggal tidak valid.'); return } const adjusted = new Date(Date.UTC(y, m - 1, d + (night ? 1 : 0))); setResult(hitungWeton(adjusted.getUTCFullYear(), adjusted.getUTCMonth() + 1, adjusted.getUTCDate())); }
  const shareText = result ? `Weton saya ${result.weton}, neptu ${result.neptu}, wuku ${result.wuku}.` : ''
  return <WetonShell><section className="weton-hero"><p className="eyebrow"><span /> Tradisi Jawa <span /></p><h1>Cek Weton & Wuku</h1><p>Kenali hari lahir, pasaran, neptu, dan wuku sebagai ruang refleksi dari budaya Jawa.</p></section><section className="weton-content"><div className="weton-form-card"><SectionTitle eyebrow="Mulai dari sini" title="Kapan kamu lahir?" /><DateField id="birth-date" label="Tanggal lahir" value={date} onChange={setDate} /><label className="weton-check"><input type="checkbox" checked={maghrib} onChange={(e) => setMaghrib(e.target.checked)} /> Saya lahir setelah Maghrib <span>(tanggal Jawa bergeser ke hari berikutnya)</span></label>{error && <p className="weton-error" role="alert">{error}</p>}<button className="button button-gold weton-submit" type="button" onClick={() => calculate()}>Lihat weton saya <Arrow /></button></div>{result && <div className="weton-output" aria-live="polite"><div className="weton-output-grid"><WetonCard result={result} /><article className="wuku-card"><p className="eyebrow">Wuku ke-{result.wukuNo}</p><h2>{result.wuku}</h2><p><strong>{result.wukuInfo.dewa}</strong><br />{result.wukuInfo.watak}</p></article></div><p className="weton-date">Dihitung dari {formatDate(date)}{maghrib ? ' (disesuaikan +1 hari)' : ''}</p><div className="weton-info-grid"><InfoBlock title="Watak" text={result.info.watak} /><InfoBlock title="Karir" text={result.info.karir} /><InfoBlock title="Rejeki" text={result.info.rejeki} /><InfoBlock title="Percintaan" text={result.info.percintaan} /><InfoBlock title="Masa depan" text={result.info.masaDepan} /></div><div className="ideal-card"><p className="eyebrow">Pasangan ideal</p><div className="ideal-grid">{pasanganIdeal(result.neptu).map((item) => <div key={item.kategori}><strong>{item.kategori}</strong><span>{item.weton.slice(0, 4).join(', ') || '—'}</span></div>)}</div></div><ShareButtons text={shareText} url={`${window.location.origin}/tarot/weton?tgl=${date}`} /><Disclaimer /></div>}</section></WetonShell>
}
