'use client'

import { useEffect, useState } from 'react'
import { hitungJodoh, hitungWeton } from '@/lib/weton-data'
import { Arrow, DateField, Disclaimer, formatDate, ShareButtons, WetonCard, WetonShell } from '@/components/weton-header'

export default function JodohPage() {
  const [a, setA] = useState(''); const [b, setB] = useState(''); const [result, setResult] = useState<ReturnType<typeof hitungJodoh> | null>(null); const [people, setPeople] = useState<ReturnType<typeof hitungWeton>[]>([]); const [error, setError] = useState('')
  useEffect(() => { const p = new URLSearchParams(window.location.search); const x = p.get('a') || ''; const y = p.get('b') || ''; if (x && y) { setA(x); setB(y); calculate(x, y) } }, [])
  function parse(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return null; const [y, m, d] = value.split('-').map(Number); const dt = new Date(`${value}T00:00:00`); return Number.isNaN(dt.getTime()) || dt.toISOString().slice(0, 10) !== value ? null : hitungWeton(y, m, d) }
  function calculate(x = a, y = b) { const one = parse(x); const two = parse(y); if (!one || !two) { setResult(null); setPeople([]); setError('Isi kedua tanggal lahir dengan benar.'); return } setError(''); setPeople([one, two]); setResult(hitungJodoh(one.neptu, two.neptu)) }
  const text = result ? `Hasil cek jodoh: ${people[0]?.weton} + ${people[1]?.weton} = ${result.kategori} (${result.total}).` : ''
  return <WetonShell><section className="weton-hero"><p className="eyebrow"><span /> Tradisi Jawa <span /></p><h1>Cek Jodoh</h1><p>Bandingkan neptu dua weton dengan cara yang ringan, reflektif, dan berakar pada budaya Jawa.</p></section><section className="weton-content"><div className="weton-form-card"><div className="section-heading"><p className="eyebrow"><span /> Dua tanggal <span /></p><h2>Siapa yang ingin kamu bandingkan?</h2></div><DateField id="person-a" label="Tanggal lahir pertama" value={a} onChange={setA} /><DateField id="person-b" label="Tanggal lahir kedua" value={b} onChange={setB} />{error && <p className="weton-error" role="alert">{error}</p>}<button className="button button-gold weton-submit" type="button" onClick={() => calculate()}>Lihat kecocokan <Arrow /></button></div>{result && <div className="weton-output" aria-live="polite"><div className="weton-output-grid"><WetonCard result={people[0]} label={`Orang pertama · ${formatDate(a)}`} /><WetonCard result={people[1]} label={`Orang kedua · ${formatDate(b)}`} /></div><article className="compatibility-card"><p className="eyebrow">Total neptu {result.total}</p><h2>{result.kategori}</h2><p>{result.makna}</p><strong>Saran: jadikan hasil ini awal percakapan yang jujur, bukan keputusan yang mengikat.</strong></article><ShareButtons text={text} url={`${window.location.origin}/tarot/jodoh?a=${a}&b=${b}`} /><Disclaimer /></div>}</section></WetonShell>
}
