'use client'

import { useEffect, useMemo, useState } from 'react'

const majors = ['The Fool','The Magician','The High Priestess','The Empress','The Emperor','The Hierophant','The Lovers','The Chariot','Strength','The Hermit','Wheel of Fortune','Justice','The Hanged Man','Death','Temperance','The Devil','The Tower','The Star','The Moon','The Sun','Judgement','The World']
const suits = { Wands: ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'], Cups: ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'], Swords: ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'], Pentacles: ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'] }
const roman = ['0','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI']
const palette = ['gold','sage','rose','gold'] as const

type TarotCard = { name: string; group: string; number: string; symbol: string; keywords: string; upright: string; reversed: string }

const cards: TarotCard[] = [
  ...majors.map((name, i) => ({ name, group: 'Major Arcana', number: roman[i], symbol: ['✦','✧','☽','✿','♜','◌','♡','↗','∞','◒','◉','⚖','◇','☼','◌','♄','⚡','✦','☽','◉','✧','◎'][i], keywords: ['beginnings · trust · possibility','will · focus · creation','intuition · mystery · inner voice','nourishment · abundance · growth','structure · leadership · stability','tradition · teaching · devotion','choice · harmony · connection','movement · determination · direction','courage · patience · compassion','solitude · wisdom · searching','cycles · change · luck','balance · truth · consequence','surrender · perspective · pause','release · transformation · renewal','harmony · patience · flow','attachment · shadow · desire','sudden change · revelation · freedom','hope · healing · inspiration','intuition · dreams · uncertainty','joy · clarity · vitality','awakening · reflection · calling','completion · wholeness · journey'][i], upright: ['Trust the first step. Something new is asking to be met with an open heart.','Your tools are already in your hands. Begin with what you know.','Let quiet knowledge lead before the noise of certainty.','Let what you nurture have room to grow.','Create the boundaries that let your vision become real.','Look for wisdom in what has been passed down.','Choose what brings you closer to yourself.','Gather your energy and move with intention.','Gentleness is a form of strength.','Make space for the answer to arrive from within.','You are part of a larger turning. Stay open.','Let truth be kind, clear, and witnessed.','A pause can reveal a path that force cannot.','What is ending is making room for what is true.','Small adjustments can return you to balance.','Notice what has more power over you than you give it.','A breakthrough can feel like disruption before it feels like freedom.','Hope is a practice. Follow the small light.','Not everything needs to be solved in the dark.','Let joy be evidence that you are on your way.','Hear the invitation beneath the old story.','Honor how far you have come.'][i], reversed: 'Turn inward and notice where this energy feels blocked or ready for a gentler approach.' })),
  ...Object.entries(suits).flatMap(([suit, names]) => names.map((name, i) => ({ name: `${name} of ${suit}`, group: suit, number: i === 0 ? 'A' : i < 10 ? String(i + 1) : name[0], symbol: suit === 'Wands' ? '✦' : suit === 'Cups' ? '♡' : suit === 'Swords' ? '⚔' : '◇', keywords: `${suit.toLowerCase()} · reflection · movement`, upright: `Let the energy of ${suit.toLowerCase()} guide one honest next step.`, reversed: `Notice where your ${suit.toLowerCase()} energy is asking for patience and care.` })))
]

function Arrow() { return <span aria-hidden="true" className="arrow">↗</span> }
function Header() { return <header className="site-header"><a className="logo" href="/" aria-label="JOGPRO TAROT home">JOGPRO <span>TAROT</span></a><nav className="main-nav" aria-label="Main navigation"><a href="/#spreads">Tarot Reading</a><a href="/tarot/cards">Card Meanings</a><a href="/tarot/daily">Daily</a><a href="/#about">About</a></nav><a className="header-cta" href="/tarot/daily">Free Reading <Arrow /></a></header> }

export default function CardLibraryPage() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [selected, setSelected] = useState<TarotCard | null>(null)
  const filtered = useMemo(() => cards.filter(card => (filter === 'All' || card.group === filter) && card.name.toLowerCase().includes(query.toLowerCase())), [filter, query])
  useEffect(() => { document.body.style.overflow = selected ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [selected])
  return <main className="library-page"><Header /><section className="library-hero"><p className="eyebrow"><span /> The complete deck <span /></p><h1>Card <em>Meanings</em></h1><p>Explore the symbols, stories, and invitations held in all 78 cards.</p></section><section className="library-content" aria-label="Tarot card library"><div className="library-controls"><label className="search-box"><span className="sr-only">Search cards</span><span aria-hidden="true">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search the deck..." /></label><div className="filter-row" role="tablist" aria-label="Filter cards">{['All','Major Arcana','Wands','Cups','Swords','Pentacles'].map(item => <button key={item} role="tab" aria-selected={filter === item} className={filter === item ? 'filter-chip active' : 'filter-chip'} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="library-meta"><span>{filtered.length} cards</span><span>Rider–Waite inspired</span></div><div className="library-grid">{filtered.map((card, i) => <button className={`library-card ${palette[i % palette.length]}`} key={card.name} onClick={() => setSelected(card)}><span className="library-card-inner"><span className="card-number">{card.number}</span><span className="library-symbol">{card.symbol}</span><span className="card-name">{card.name}</span><span className="library-group">{card.group}</span></span></button>)}</div>{filtered.length === 0 && <p className="empty-library">No cards found. Try another question.</p>}</section><footer className="site-footer"><a className="logo" href="/">JOGPRO <span>TAROT</span></a><p>Read inward. Move forward.</p><span className="footer-note">© 2026 JOGPRO TAROT</span></footer>{selected && <div className="modal-backdrop" role="presentation" onClick={e => e.target === e.currentTarget && setSelected(null)}><article className="card-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close card details">×</button><div className="modal-card"><span>{selected.number}</span><strong>{selected.symbol}</strong><b>{selected.name}</b></div><p className="eyebrow sage-text">{selected.group}</p><h2 id="modal-title">{selected.name}</h2><p className="modal-keywords">{selected.keywords}</p><div className="meaning-grid"><div><small>Upright</small><p>{selected.upright}</p></div><div><small>Reversed</small><p>{selected.reversed}</p></div></div><p className="modal-prompt">What does this card make you curious about?</p></article></div>}</main>
}
